name: 'Exact Dependency Checker'
description: 'Validates whether a project uses version-specific dependencies only'
branding:
  color: "green"
  icon: "check-circle"
inputs:
  milliseconds: # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'



